package com.wireless.agent.tools;

import com.wireless.agent.core.Spec;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

/** Generates PR + ticket + one-shot submission script from spec + code. */
public class SchedulerTool implements Tool {

    private static final DateTimeFormatter DT_FMT =
            DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss");
    private static final List<String> VALID_ENGINES = List.of(
            "spark_sql", "flink_sql", "java_flink_streamapi");

    @Override
    public String name() { return "scheduler"; }

    @Override
    public String description() {
        return "从 spec + 代码生成 PR 模板、上线工单和一次性 spark-submit/flink run 提交脚本";
    }

    @Override
    public ToolResult run(Spec spec) {
        return ToolResult.fail("Use run(spec, code) with generated code");
    }

    /** Main entry: generate all three artifacts. */
    public ToolResult run(Spec spec, String code) {
        if (spec.state() != Spec.SpecState.CODEGEN_DONE) {
            return ToolResult.fail("Spec not ready for deployment: state="
                    + spec.state().value() + ", need codegen_done");
        }
        if (code == null || code.isBlank()) {
            return ToolResult.fail("No code to deploy");
        }

        var targetName = spec.target() != null ? spec.target().name() : "unnamed_task";
        var engine = spec.engineDecision() != null
                ? spec.engineDecision().recommended() : "spark_sql";

        var submitScript = generateSubmitScript(engine, targetName, code);
        var prTemplate = generatePrTemplate(spec, code, targetName);
        var ticketTemplate = generateTicketTemplate(spec, code, targetName, engine);
        var codeHash = sha256(code);

        return ToolResult.ok(Map.of(
            "submit_script", submitScript,
            "pr_template", prTemplate,
            "ticket_template", ticketTemplate,
            "code_hash", codeHash,
            "engine", engine,
            "target_name", targetName,
            "generated_at", LocalDateTime.now().format(DT_FMT)
        ));
    }

    /** Generate one-shot submission script based on engine type. */
    String generateSubmitScript(String engine, String targetName, String code) {
        var ts = LocalDateTime.now().format(DT_FMT);
        var jobName = targetName + "_" + ts;

        return switch (engine) {
            case "spark_sql" -> String.format("""
                    #!/bin/bash
                    # One-shot Spark SQL job — generated by Data Agent
                    # Target: %s
                    # Generated: %s

                    SQL_CODE='%s'

                    spark-submit \\
                      --master yarn \\
                      --deploy-mode cluster \\
                      --name "%s" \\
                      --queue root.prod.wireless \\
                      --conf spark.sql.adaptive.enabled=true \\
                      --conf spark.sql.adaptive.coalescePartitions.enabled=true
                    """, targetName, ts, escapeForShell(code), jobName);

            case "flink_sql" -> String.format("""
                    #!/bin/bash
                    # One-shot Flink SQL job — generated by Data Agent
                    # Target: %s
                    # Generated: %s

                    echo '%s' | \\
                      /opt/flink/bin/sql-client.sh \\
                      -j /opt/flink/lib/flink-sql-connector-kafka.jar
                    """, targetName, ts, escapeForShell(code));

            case "java_flink_streamapi" -> String.format("""
                    #!/bin/bash
                    # One-shot Flink Stream API job — generated by Data Agent
                    # Target: %s
                    # Generated: %s

                    flink run \\
                      --jobmanager flink-jobmanager:8081 \\
                      --class com.wireless.agent.generated.%sJob \\
                      --parallelism 4 \\
                      target/data-agent-0.1.0.jar
                    """, targetName, ts, sanitizeClassName(targetName));

            default -> "# Unknown engine: " + engine;
        };
    }

    /** Generate PR markdown template. */
    String generatePrTemplate(Spec spec, String code, String targetName) {
        var sb = new StringBuilder();
        sb.append("# Data Agent Generated: ").append(targetName).append("\n\n");

        sb.append("## 变更内容\n\n");
        sb.append("新增数据集: `").append(targetName).append("`\n\n");

        var target = spec.target();
        if (target != null && !target.businessDefinition().isEmpty()) {
            sb.append("**业务口径:** ").append(target.businessDefinition()).append("\n\n");
        }
        if (target != null && !target.timeliness().isEmpty()) {
            sb.append("**时效性:** ").append(target.timeliness()).append("\n\n");
        }

        sb.append("## 代码\n\n");
        var engine = spec.engineDecision() != null
                ? spec.engineDecision().recommended() : "spark_sql";
        sb.append("```").append(engine.equals("java_flink_streamapi") ? "java" : "sql").append("\n");
        sb.append(code).append("\n");
        sb.append("```\n\n");

        sb.append("## 数据源\n\n");
        for (var src : spec.sources()) {
            var tbl = src.binding().getOrDefault("table_or_topic", "").toString();
            var cat = src.binding().getOrDefault("catalog", "unknown").toString();
            sb.append("- ").append(cat).append(": `").append(tbl).append("`");
            if (src.confidence() > 0) {
                sb.append(" (confidence: ").append(String.format("%.0f%%", src.confidence() * 100)).append(")");
            }
            sb.append("\n");
        }
        sb.append("\n");

        sb.append("## Owner / Reviewers\n\n");
        var upstream = spec.owners().get("upstream");
        if (upstream != null && !upstream.isEmpty()) {
            sb.append("**上游数据 owner:** ");
            sb.append(upstream.stream().map(o -> "@" + o).collect(Collectors.joining(", ")));
            sb.append("\n\n");
        }
        var downstream = spec.owners().get("downstream");
        if (downstream != null && !downstream.isEmpty()) {
            sb.append("**下游消费方:** ");
            sb.append(String.join(", ", downstream));
            sb.append("\n\n");
        }

        sb.append("## 测试用例\n\n");
        if (!spec.testCases().isEmpty()) {
            sb.append("| 用例 | 输入 | 期望输出 |\n");
            sb.append("|------|------|----------|\n");
            for (var tc : spec.testCases()) {
                var name = tc.getOrDefault("name", "-").toString();
                var inputs = tc.getOrDefault("inputs", "-").toString();
                var expected = tc.getOrDefault("expected_output", "-").toString();
                sb.append("| ").append(name).append(" | ").append(inputs)
                        .append(" | ").append(expected).append(" |\n");
            }
        } else {
            sb.append("(无预置测试用例)\n");
        }
        sb.append("\n");

        sb.append("## 引擎选择\n\n");
        if (spec.engineDecision() != null) {
            sb.append("**引擎:** ").append(spec.engineDecision().recommended()).append("\n");
            sb.append("**理由:** ").append(spec.engineDecision().reasoning()).append("\n");
        }
        sb.append("\n---\n_由 Data Agent 自动生成_");

        return sb.toString();
    }

    /** Generate ticket/change-request markdown template. */
    String generateTicketTemplate(Spec spec, String code, String targetName, String engine) {
        var sb = new StringBuilder();
        sb.append("# 上线工单 — ").append(targetName).append("\n\n");

        sb.append("| 字段 | 值 |\n");
        sb.append("|------|-----|\n");
        sb.append("| **任务名** | ").append(targetName).append(" |\n");
        sb.append("| **引擎** | ").append(engine).append(" |\n");
        sb.append("| **生成时间** | ").append(LocalDateTime.now().format(DT_FMT)).append(" |\n");

        var target = spec.target();
        sb.append("| **时效性** | ").append(target != null ? target.timeliness() : "-").append(" |\n");
        sb.append("| **状态** | 待 review |\n\n");

        sb.append("## 业务口径\n\n");
        sb.append(target != null && !target.businessDefinition().isEmpty()
                ? target.businessDefinition() : "(待确认)");
        sb.append("\n\n");

        sb.append("## test_case\n\n");
        if (!spec.testCases().isEmpty()) {
            for (var tc : spec.testCases()) {
                for (var entry : tc.entrySet()) {
                    sb.append("- ").append(entry.getKey()).append(": ").append(entry.getValue()).append("\n");
                }
            }
            sb.append("\n");
        } else {
            sb.append("(无预置测试用例)\n\n");
        }

        sb.append("## 提交方式\n\n");
        sb.append("一次性 job 提交脚本已生成，执行方式:\n\n");
        sb.append("```bash\n");
        sb.append("# 将此脚本在目标集群上执行\n");
        sb.append("chmod +x submit_").append(sanitizeClassName(targetName)).append(".sh\n");
        sb.append("./submit_").append(sanitizeClassName(targetName)).append(".sh\n");
        sb.append("```\n\n");

        sb.append("## 验证清单\n\n");
        sb.append("- [ ] 代码 review 通过\n");
        sb.append("- [ ] 测试用例 (").append(spec.testCases().size()).append(" 条) 验证通过\n");
        sb.append("- [ ] Dry-run 结果确认\n");
        sb.append("- [ ] 上游数据 owner 知会\n");
        sb.append("- [ ] 下游消费方通知\n\n");

        sb.append("## 回滚方案\n\n");
        sb.append("若输出数据异常:\n");
        sb.append("1. 删除输出表 `").append(targetName).append("`\n");
        sb.append("2. 修正代码后重新提交\n");
        sb.append("3. 必要时通知下游消费方\n\n");

        sb.append("---\n_由 Data Agent 自动生成_");
        return sb.toString();
    }

    private String escapeForShell(String s) {
        return s.replace("\\", "\\\\")
                .replace("'", "'\\''")
                .replace("\"", "\\\"")
                .replace("\n", "\\n");
    }

    private String sanitizeClassName(String name) {
        return name.replaceAll("[^a-zA-Z0-9_]", "_");
    }

    private String sha256(String input) {
        try {
            var md = MessageDigest.getInstance("SHA-256");
            var bytes = md.digest(input.getBytes());
            var sb = new StringBuilder();
            for (var b : bytes) sb.append(String.format("%02x", b));
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            return Integer.toHexString(input.hashCode());
        }
    }
}
